# fly.toml app configuration file generated for culin-backend-dev on 2025-05-31T00:46:38+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'culin-backend-dev'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 6996
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
