app = "culai-backend"
primary_region = "maa"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
  [[services.ports]]
    port = 443

  [[services.http_checks]]
    interval = "15s"
    timeout = "3s"
    method = "get"
    path = "/healthz"
    protocol = "http"
    tls_skip_verify = false
