app = "culai-backend"
primary_region = "maa"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 0
  processes = ["app"]

  [[http_service.ports]]
    port = 80
  [[http_service.ports]]
    port = 443

  [[http_service.checks]]
    interval = "15s"
    timeout = "3s"
    method = "get"
    path = "/healthz"
    protocol = "http"
    tls_skip_verify = false
